// GENERATED by scripts/build-klarna-vo.mjs — do not edit by hand.
// Source of truth for what lands where: scripts/klarna-edit.mjs.

export const FPS = 30;
export const TOTAL_FRAMES = 1531;

export type Move = {push?: number; dx?: number; dy?: number};
export type Num =
  | {kind: 'hook'; text: string; sub: string}
  | {kind: 'chip'; text: string}
  | {kind: 'split'; from: string; to: string; note: string}
  | {kind: 'arrow'; from: string; to: string}
  | {kind: 'alert'; text: string}
  | {kind: 'locked'; text: string; sub: string}
  | {kind: 'sum'; text: string}
  | {kind: 'cracked'; text: string};

export type Shot = {
  id: string;
  still: number;
  from: number;
  durationInFrames: number;
  speech: [number, number];
  move: Move;
  cold: boolean;
  figureY: number;
  cap: string;
  num: Num | null;
};

export const SHOTS: Shot[] = [
  {
    "id": "F01",
    "still": 1,
    "from": 0,
    "durationInFrames": 91,
    "speech": [
      4,
      61
    ],
    "move": {
      "push": 0.06
    },
    "cold": false,
    "figureY": 545,
    "cap": "Four payments.\nZero interest.",
    "num": {
      "kind": "hook",
      "text": "4 payments of £22.50",
      "sub": "0% interest"
    }
  },
  {
    "id": "F02A",
    "still": 2,
    "from": 91,
    "durationInFrames": 72,
    "speech": [
      95,
      145
    ],
    "move": {
      "push": 0.04
    },
    "cold": false,
    "figureY": 655,
    "cap": "Four payments of\n£22.50.",
    "num": {
      "kind": "chip",
      "text": "£22.50 × 4  =  £90"
    }
  },
  {
    "id": "F02B",
    "still": 3,
    "from": 163,
    "durationInFrames": 98,
    "speech": [
      167,
      243
    ],
    "move": {
      "push": -0.08,
      "dx": -30
    },
    "cold": false,
    "figureY": 655,
    "cap": "So who is paying\nfor it?",
    "num": {
      "kind": "chip",
      "text": "the fifth payment: ?"
    }
  },
  {
    "id": "F03",
    "still": 4,
    "from": 261,
    "durationInFrames": 81,
    "speech": [
      265,
      325
    ],
    "move": {
      "push": 0.05
    },
    "cold": false,
    "figureY": 800,
    "cap": "The shop does not\nreceive £90.",
    "num": {
      "kind": "split",
      "from": "£90",
      "to": "£85",
      "note": "−6% to Klarna"
    }
  },
  {
    "id": "F04",
    "still": 5,
    "from": 342,
    "durationInFrames": 92,
    "speech": [
      346,
      419
    ],
    "move": {
      "push": 0.09
    },
    "cold": false,
    "figureY": 800,
    "cap": "It builds it into\nthe sticker.",
    "num": {
      "kind": "arrow",
      "from": "£90.00",
      "to": "£95.40"
    }
  },
  {
    "id": "F05A",
    "still": 6,
    "from": 434,
    "durationInFrames": 78,
    "speech": [
      438,
      499
    ],
    "move": {
      "push": 0.1
    },
    "cold": false,
    "figureY": 780,
    "cap": "The price goes up.\nFor everyone.",
    "num": null
  },
  {
    "id": "F05B",
    "still": 7,
    "from": 512,
    "durationInFrames": 101,
    "speech": [
      517,
      599
    ],
    "move": {
      "push": 0.06
    },
    "cold": false,
    "figureY": 780,
    "cap": "Including the man\npaying cash.",
    "num": null
  },
  {
    "id": "F06A",
    "still": 8,
    "from": 613,
    "durationInFrames": 65,
    "speech": [
      617,
      660
    ],
    "move": {
      "push": 0.07,
      "dy": 20
    },
    "cold": false,
    "figureY": 780,
    "cap": "He pays for it\nanyway.",
    "num": null
  },
  {
    "id": "F06B",
    "still": 9,
    "from": 678,
    "durationInFrames": 89,
    "speech": [
      683,
      749
    ],
    "move": {
      "push": 0.08
    },
    "cold": true,
    "figureY": 790,
    "cap": "Then the late fee.",
    "num": {
      "kind": "alert",
      "text": "LATE FEE"
    }
  },
  {
    "id": "F07A",
    "still": 10,
    "from": 767,
    "durationInFrames": 112,
    "speech": [
      771,
      868
    ],
    "move": {
      "push": 0.06,
      "dy": -40
    },
    "cold": false,
    "figureY": 800,
    "cap": "Split it in four,\nand people spend more.",
    "num": {
      "kind": "chip",
      "text": "BIGGER BASKET"
    }
  },
  {
    "id": "F07B",
    "still": 11,
    "from": 879,
    "durationInFrames": 130,
    "speech": [
      883,
      994
    ],
    "move": {
      "push": 0.05
    },
    "cold": false,
    "figureY": 780,
    "cap": "That's not a side effect.\nThat's the product.",
    "num": null
  },
  {
    "id": "F08",
    "still": 12,
    "from": 1009,
    "durationInFrames": 106,
    "speech": [
      1014,
      1085
    ],
    "move": {},
    "cold": false,
    "figureY": 1330,
    "cap": "One price.\nOne owner.\nNo penalty.",
    "num": {
      "kind": "locked",
      "text": "£90.00",
      "sub": "LOCKED"
    }
  },
  {
    "id": "F09",
    "still": 13,
    "from": 1115,
    "durationInFrames": 70,
    "speech": [
      1119,
      1164
    ],
    "move": {
      "dx": 30
    },
    "cold": false,
    "figureY": 790,
    "cap": "It's called murabaha.",
    "num": {
      "kind": "sum",
      "text": "COST £75  +  MARKUP £15  =  £90 FIXED"
    }
  },
  {
    "id": "F10",
    "still": 14,
    "from": 1185,
    "durationInFrames": 75,
    "speech": [
      1189,
      1243
    ],
    "move": {
      "push": 0.12
    },
    "cold": false,
    "figureY": 1545,
    "cap": "\"Pay later\" was never\nthe problem.",
    "num": {
      "kind": "cracked",
      "text": "£90.00"
    }
  },
  {
    "id": "F11A",
    "still": 15,
    "from": 1260,
    "durationInFrames": 108,
    "speech": [
      1264,
      1353
    ],
    "move": {
      "push": 0.04
    },
    "cold": false,
    "figureY": 800,
    "cap": "The problem is who\nearns on the \"later\".",
    "num": {
      "kind": "chip",
      "text": "0% is never zero"
    }
  },
  {
    "id": "F11B",
    "still": 16,
    "from": 1368,
    "durationInFrames": 163,
    "speech": [
      1372,
      1512
    ],
    "move": {
      "push": 0.03
    },
    "cold": false,
    "figureY": 780,
    "cap": "Three questions.\nAsk them before you click.",
    "num": null
  }
];
