// GENERATED by scripts/build-klarna.mjs — do not edit by hand.
// Source of truth for what lands where: scripts/klarna-edit.mjs.

export const FPS = 30;
export const TOTAL_FRAMES = 5198;

export type Move = {push?: number; dx?: number; dy?: number};
export type Num =
  | {kind: 'hook'; text: string; sub: string}
  | {kind: 'chip'; text: string}
  | {kind: 'split'; from: string; to: string; note: string}
  | {kind: 'arrow'; from: string; to: string}
  | {kind: 'alert'; text: string}
  | {kind: 'locked'; text: string; sub: string}
  | {kind: 'sum'; text: string}
  | {kind: 'cracked'; text: string};

export type Shot = {
  from: number;
  durationInFrames: number;
  still: number | null;
  gap: number | null;
  card: any | null;
  move: Move;
  cold: boolean;
  figureY: number;
  cap: string | null;
  num: Num | null;
};

export const SHOTS: Shot[] = [
  {
    "from": 0,
    "durationInFrames": 78,
    "still": 1,
    "gap": null,
    "card": null,
    "move": {
      "push": 0.06
    },
    "cold": false,
    "figureY": 545,
    "cap": "Four payments.\nZero interest.",
    "num": {
      "kind": "hook",
      "text": "4 payments of £22.50",
      "sub": "0% interest"
    }
  },
  {
    "from": 78,
    "durationInFrames": 102,
    "still": 3,
    "gap": null,
    "card": null,
    "move": {
      "push": -0.08,
      "dx": -30
    },
    "cold": false,
    "figureY": 655,
    "cap": "So who is paying\nfor it?",
    "num": {
      "kind": "chip",
      "text": "the fifth payment: ?"
    }
  },
  {
    "from": 180,
    "durationInFrames": 66,
    "still": null,
    "gap": null,
    "card": {
      "type": "statement",
      "text": "Because somebody is.",
      "bg": 3
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 246,
    "durationInFrames": 93,
    "still": null,
    "gap": null,
    "card": {
      "type": "statement",
      "text": "And it might be you.",
      "sub": "Just not where you’re looking.",
      "bg": 3
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 339,
    "durationInFrames": 153,
    "still": null,
    "gap": null,
    "card": {
      "type": "statement",
      "text": "Klarna does not\nlend you money.",
      "accent": "not",
      "bg": 1
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 492,
    "durationInFrames": 135,
    "still": 4,
    "gap": null,
    "card": null,
    "move": {
      "push": 0.05
    },
    "cold": false,
    "figureY": 780,
    "cap": "It pays the shop.\nToday. In full.",
    "num": null
  },
  {
    "from": 627,
    "durationInFrames": 51,
    "still": null,
    "gap": null,
    "card": {
      "type": "flow",
      "nodes": [
        "KLARNA",
        "THE SHOP",
        "YOU"
      ],
      "lit": 2,
      "bg": 4
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": "Then you owe Klarna.",
    "num": null
  },
  {
    "from": 678,
    "durationInFrames": 60,
    "still": null,
    "gap": null,
    "card": {
      "type": "statement",
      "text": "It decides everything.",
      "bg": 4
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 738,
    "durationInFrames": 41,
    "still": 5,
    "gap": null,
    "card": null,
    "move": {
      "push": 0.09
    },
    "cold": false,
    "figureY": 780,
    "cap": "A £90 jacket.",
    "num": null
  },
  {
    "from": 779,
    "durationInFrames": 73,
    "still": 2,
    "gap": null,
    "card": null,
    "move": {
      "push": 0.04
    },
    "cold": false,
    "figureY": 655,
    "cap": "Four payments\nof £22.50.",
    "num": {
      "kind": "chip",
      "text": "£22.50 × 4  =  £90"
    }
  },
  {
    "from": 852,
    "durationInFrames": 87,
    "still": 4,
    "gap": null,
    "card": null,
    "move": {
      "push": 0.05,
      "dx": 20
    },
    "cold": false,
    "figureY": 780,
    "cap": "The shop does not\nreceive £90.",
    "num": null
  },
  {
    "from": 939,
    "durationInFrames": 84,
    "still": null,
    "gap": null,
    "card": {
      "type": "number",
      "from": "£90",
      "to": "£85",
      "note": "what the shop actually receives",
      "bg": 4
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 1023,
    "durationInFrames": 165,
    "still": null,
    "gap": null,
    "card": {
      "type": "pct",
      "label": "KLARNA KEEPS",
      "from": 3,
      "to": 6,
      "bg": 2
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": "Often 3 to 6%.",
    "num": null
  },
  {
    "from": 1188,
    "durationInFrames": 60,
    "still": 3,
    "gap": null,
    "card": null,
    "move": {
      "push": 0.06
    },
    "cold": false,
    "figureY": 655,
    "cap": "So where did that\n£5 come from?",
    "num": {
      "kind": "chip",
      "text": "the missing fifth"
    }
  },
  {
    "from": 1248,
    "durationInFrames": 78,
    "still": null,
    "gap": null,
    "card": {
      "type": "ledger",
      "rows": [
        [
          "You paid",
          "£90"
        ],
        [
          "The shop kept",
          "£85"
        ]
      ],
      "bg": 2
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 1326,
    "durationInFrames": 90,
    "still": null,
    "gap": null,
    "card": {
      "type": "statement",
      "text": "It was already\ninside the price.",
      "accent": "already",
      "bg": 5
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 1416,
    "durationInFrames": 126,
    "still": null,
    "gap": null,
    "card": {
      "type": "statement",
      "text": "No shop absorbs\nthat fee.",
      "bg": 5
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 1542,
    "durationInFrames": 105,
    "still": 5,
    "gap": null,
    "card": null,
    "move": {
      "push": 0.09
    },
    "cold": false,
    "figureY": 800,
    "cap": "It builds it into\nthe sticker.",
    "num": {
      "kind": "arrow",
      "from": "£90.00",
      "to": "£95.40"
    }
  },
  {
    "from": 1647,
    "durationInFrames": 80,
    "still": 6,
    "gap": null,
    "card": null,
    "move": {
      "push": 0.1
    },
    "cold": false,
    "figureY": 780,
    "cap": "The price goes up.\nFor everyone.",
    "num": null
  },
  {
    "from": 1727,
    "durationInFrames": 49,
    "still": 7,
    "gap": null,
    "card": null,
    "move": {
      "push": 0.06
    },
    "cold": false,
    "figureY": 780,
    "cap": "Including the man\npaying cash.",
    "num": null
  },
  {
    "from": 1776,
    "durationInFrames": 146,
    "still": 8,
    "gap": null,
    "card": null,
    "move": {
      "push": 0.07,
      "dy": 20
    },
    "cold": false,
    "figureY": 780,
    "cap": "He never used Klarna.\nHe pays for it anyway.",
    "num": null
  },
  {
    "from": 1922,
    "durationInFrames": 100,
    "still": 9,
    "gap": null,
    "card": null,
    "move": {
      "push": 0.05
    },
    "cold": true,
    "figureY": 780,
    "cap": "Then there is\nbeing late.",
    "num": null
  },
  {
    "from": 2022,
    "durationInFrames": 90,
    "still": 9,
    "gap": null,
    "card": null,
    "move": {
      "push": 0.08
    },
    "cold": true,
    "figureY": 790,
    "cap": "Where late fees apply,\nthat is revenue.",
    "num": {
      "kind": "alert",
      "text": "LATE FEE"
    }
  },
  {
    "from": 2112,
    "durationInFrames": 63,
    "still": null,
    "gap": null,
    "card": {
      "type": "statement",
      "text": "A penalty that becomes\ntheir profit.",
      "accent": "profit",
      "cold": true,
      "bg": 9
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 2175,
    "durationInFrames": 123,
    "still": null,
    "gap": null,
    "card": {
      "type": "statement",
      "text": "That is the oldest\nobjection there is.",
      "bg": 9
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 2298,
    "durationInFrames": 147,
    "still": 10,
    "gap": null,
    "card": null,
    "move": {
      "push": 0.06,
      "dy": -40
    },
    "cold": false,
    "figureY": 800,
    "cap": "Split it in four,\nand people spend more.",
    "num": {
      "kind": "chip",
      "text": "BIGGER BASKET"
    }
  },
  {
    "from": 2445,
    "durationInFrames": 150,
    "still": 11,
    "gap": null,
    "card": null,
    "move": {
      "push": 0.05
    },
    "cold": false,
    "figureY": 780,
    "cap": "That's not a side effect.\nThat's the product.",
    "num": null
  },
  {
    "from": 2595,
    "durationInFrames": 56,
    "still": null,
    "gap": null,
    "card": {
      "type": "statement",
      "text": "So is it halal?",
      "big": true,
      "bg": 11
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 2651,
    "durationInFrames": 109,
    "still": null,
    "gap": null,
    "card": {
      "type": "statement",
      "text": "Don’t ask about the brand.",
      "sub": "Ask three questions.",
      "accent": "three",
      "bg": 11
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 2760,
    "durationInFrames": 114,
    "still": null,
    "gap": null,
    "card": {
      "type": "question",
      "n": "ONE",
      "q": "Is this a sale,\nor a loan?",
      "bg": 4
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 2874,
    "durationInFrames": 69,
    "still": null,
    "gap": null,
    "card": {
      "type": "flow",
      "nodes": [
        "KLARNA",
        "THE SHOP",
        "YOU"
      ],
      "lit": 2,
      "caption": "They paid the shop. You owe them.",
      "bg": 4
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 2943,
    "durationInFrames": 57,
    "still": null,
    "gap": null,
    "card": {
      "type": "verdict",
      "text": "THAT IS A LOAN",
      "bg": 4
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 3000,
    "durationInFrames": 102,
    "still": null,
    "gap": null,
    "card": {
      "type": "question",
      "n": "TWO",
      "q": "Does anybody profit\nfrom that loan?",
      "bg": 13
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 3102,
    "durationInFrames": 96,
    "still": null,
    "gap": null,
    "card": {
      "type": "ledger",
      "rows": [
        [
          "From you",
          "NO"
        ],
        [
          "From the merchant’s fee",
          "YES"
        ]
      ],
      "bg": 13
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 3198,
    "durationInFrames": 120,
    "still": null,
    "gap": null,
    "card": {
      "type": "statement",
      "text": "A loan that brings a benefit\nto the lender.",
      "accent": "benefit",
      "bg": 13
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 3318,
    "durationInFrames": 114,
    "still": null,
    "gap": null,
    "card": {
      "type": "statement",
      "text": "The exact phrase the\nscholars argue over.",
      "bg": 13
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 3432,
    "durationInFrames": 132,
    "still": null,
    "gap": null,
    "card": {
      "type": "question",
      "n": "THREE",
      "q": "Would cash have\nbeen cheaper?",
      "sub": "If later costs more than now, you paid for time.",
      "bg": 8
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 3564,
    "durationInFrames": 66,
    "still": null,
    "gap": null,
    "card": {
      "type": "verdict",
      "text": "TIME IS NOT THEIRS TO SELL",
      "bg": 8
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 3630,
    "durationInFrames": 164,
    "still": null,
    "gap": null,
    "card": {
      "type": "balance",
      "head": "Scholars genuinely differ here.",
      "left": [
        "Same price as cash",
        "No late fee",
        "No interest"
      ],
      "right": [
        "A penalty",
        "A higher price for waiting"
      ],
      "lit": "left",
      "verdict": "MANY PERMIT IT",
      "bg": 12
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 3794,
    "durationInFrames": 178,
    "still": null,
    "gap": null,
    "card": {
      "type": "balance",
      "head": "Scholars genuinely differ here.",
      "left": [
        "Same price as cash",
        "No late fee",
        "No interest"
      ],
      "right": [
        "A penalty",
        "A higher price for waiting"
      ],
      "lit": "right",
      "verdict": "THE DISAGREEMENT ENDS",
      "bg": 12
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 3972,
    "durationInFrames": 75,
    "still": null,
    "gap": null,
    "card": {
      "type": "statement",
      "text": "But here is the part\nnobody says.",
      "bg": 13
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 4047,
    "durationInFrames": 66,
    "still": null,
    "gap": null,
    "card": {
      "type": "statement",
      "text": "Buy now, pay later\nis not the problem.",
      "accent": "not",
      "bg": 13
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 4113,
    "durationInFrames": 57,
    "still": null,
    "gap": null,
    "card": {
      "type": "era",
      "text": "Islam has had it for",
      "years": "1,400 years",
      "bg": 13
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 4170,
    "durationInFrames": 75,
    "still": 13,
    "gap": null,
    "card": null,
    "move": {
      "dx": 30
    },
    "cold": false,
    "figureY": 780,
    "cap": "It's called murabaha.",
    "num": null
  },
  {
    "from": 4245,
    "durationInFrames": 141,
    "still": null,
    "gap": null,
    "card": {
      "type": "steps",
      "items": [
        "The seller buys it",
        "Actually owns it",
        "Then sells it to you"
      ],
      "bg": 13
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 4386,
    "durationInFrames": 138,
    "still": 12,
    "gap": null,
    "card": null,
    "move": {},
    "cold": false,
    "figureY": 1330,
    "cap": "One disclosed price,\nfixed at signing.",
    "num": {
      "kind": "sum",
      "text": "COST £75  +  MARKUP £15  =  £90 FIXED"
    }
  },
  {
    "from": 4524,
    "durationInFrames": 144,
    "still": null,
    "gap": null,
    "card": {
      "type": "statement",
      "text": "Paid over time.",
      "bg": 12
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 4668,
    "durationInFrames": 75,
    "still": null,
    "gap": null,
    "card": {
      "type": "statement",
      "text": "Late? You owe the same.",
      "sub": "Not a penny more.",
      "accent": "same",
      "bg": 12
    },
    "move": {},
    "cold": false,
    "figureY": 780,
    "cap": null,
    "num": null
  },
  {
    "from": 4743,
    "durationInFrames": 105,
    "still": 12,
    "gap": null,
    "card": null,
    "move": {},
    "cold": false,
    "figureY": 1330,
    "cap": "One price.\nOne owner.\nNo penalty.",
    "num": {
      "kind": "locked",
      "text": "£90.00",
      "sub": "LOCKED"
    }
  },
  {
    "from": 4848,
    "durationInFrames": 90,
    "still": 14,
    "gap": null,
    "card": null,
    "move": {
      "push": 0.12
    },
    "cold": false,
    "figureY": 1545,
    "cap": "\"Pay later\" was never\nthe problem.",
    "num": {
      "kind": "cracked",
      "text": "£90.00"
    }
  },
  {
    "from": 4938,
    "durationInFrames": 102,
    "still": 14,
    "gap": null,
    "card": null,
    "move": {
      "push": 0.06
    },
    "cold": false,
    "figureY": 780,
    "cap": "The problem is who\nearns on the \"later\".",
    "num": null
  },
  {
    "from": 5040,
    "durationInFrames": 78,
    "still": 15,
    "gap": null,
    "card": null,
    "move": {
      "push": 0.04
    },
    "cold": false,
    "figureY": 800,
    "cap": "Three questions.",
    "num": {
      "kind": "chip",
      "text": "0% is never zero"
    }
  },
  {
    "from": 5118,
    "durationInFrames": 80,
    "still": 16,
    "gap": null,
    "card": null,
    "move": {
      "push": 0.03
    },
    "cold": false,
    "figureY": 780,
    "cap": "Ask them before\nyou click.",
    "num": null
  }
];
