// Prepares everything the Klarna composition needs from the supplied .mov:
//
//   public/klarna-vo.m4a        the voiceover, taken whole and untouched
//   public/broll/klarna/*.jpg   the 16 stills, one per 3.00s block
//   src/klarna/timing.ts        frame-exact shot table
//   ../media/klarna.srt         subtitles for the full script
//
// The audio is NOT re-cut. An earlier pass shortened the film to 51s by selecting
// sentences; that is reverted — the brief is the film at its supplied length, with
// the 125 seconds of missing picture covered by motion graphics instead.
//
// Usage: node scripts/build-klarna.mjs /path/to/source.mov

import {execFileSync} from 'node:child_process';
import {mkdirSync, writeFileSync, copyFileSync, readFileSync, existsSync} from 'node:fs';
import path from 'node:path';
import {FPS, SHOTS, TOTAL, durations} from './klarna-edit.mjs';

const SRC = process.argv[2];
if (!SRC) throw new Error('usage: build-klarna.mjs <source.mov>');

// ffmpeg comes from the imageio wheel; this box has no system ffmpeg.
const FF = execFileSync('python3', [
  '-c',
  'import imageio_ffmpeg;print(imageio_ffmpeg.get_ffmpeg_exe())',
])
  .toString()
  .trim();
const ff = (args) => execFileSync(FF, ['-hide_banner', '-loglevel', 'error', ...args]);

// ── stills ───────────────────────────────────────────────────────────────────
// The source cuts every 3.00s. Sample the middle of each block, well clear of
// both boundaries, and keep the native 1072x1920 — the composition covers the
// 8px difference rather than stretching it.
const BROLL = path.resolve('public/broll/klarna');
mkdirSync(BROLL, {recursive: true});
for (let i = 0; i < 16; i += 1) {
  const out = path.join(BROLL, `klarna-${String(i + 1).padStart(2, '0')}.jpg`);
  if (existsSync(out)) continue;
  ff(['-ss', String(i * 3 + 1.5), '-i', SRC, '-frames:v', '1', '-q:v', '2', out, '-y']);
}

// ── voiceover, whole ─────────────────────────────────────────────────────────
// Loudness only. -14 LUFS is YouTube's normalisation target: louder just gets
// turned back down, quieter loses against everything around it in the feed.
mkdirSync(path.resolve('../media'), {recursive: true});
const VO = path.resolve('../media/klarna-vo.m4a');
ff(['-i', SRC, '-map', '0:a', '-af', 'loudnorm=I=-14:TP=-1.5:LRA=11,aresample=48000',
    '-ar', '48000', '-c:a', 'aac', '-b:a', '192k', VO, '-y']);
copyFileSync(VO, path.resolve('public/klarna-vo.m4a'));

// ── timing ───────────────────────────────────────────────────────────────────
// Gap frames adopt themselves. A card whose gap-NN.jpg has been generated stops
// being type-on-a-blurred-reuse and becomes a real shot: its own frame, sharp,
// carrying the MOVE from klarna-gap-frames.txt, with the same type over it. Until
// then it falls back to `bg`. So generation and wiring are decoupled — drop the
// files in and rebuild, nothing else changes.
const gapPath = (n) => `public/broll/klarna/gap-${String(n).padStart(2, '0')}.jpg`;
const haveGap = (n) => (n ? existsSync(path.resolve(gapPath(n))) : false);
const gapsFound = SHOTS.filter((s) => haveGap(s.gap)).length;

const dur = durations();
const shots = SHOTS.map((s, i) => ({
  from: Math.round(s.at * FPS),
  durationInFrames: Math.round((s.at + dur[i]) * FPS) - Math.round(s.at * FPS),
  still: s.still ?? null,
  gap: haveGap(s.gap) ? s.gap : null,
  card: s.card ?? null,
  move: (haveGap(s.gap) ? s.gapMove : s.move) ?? {},
  cold: !!s.cold,
  figureY: s.figureY ?? 780,
  cap: s.cap ?? null,
  num: s.num ?? null,
}));
const totalFrames = shots.at(-1).from + shots.at(-1).durationInFrames;

mkdirSync(path.resolve('src/klarna'), {recursive: true});
writeFileSync(
  path.resolve('src/klarna/timing.ts'),
  `// GENERATED by scripts/build-klarna.mjs — do not edit by hand.\n` +
    `// Source of truth for what lands where: scripts/klarna-edit.mjs.\n\n` +
    `export const FPS = ${FPS};\n` +
    `export const TOTAL_FRAMES = ${totalFrames};\n\n` +
    `export type Move = {push?: number; dx?: number; dy?: number};\n` +
    `export type Num =\n` +
    `  | {kind: 'hook'; text: string; sub: string}\n` +
    `  | {kind: 'chip'; text: string}\n` +
    `  | {kind: 'split'; from: string; to: string; note: string}\n` +
    `  | {kind: 'arrow'; from: string; to: string}\n` +
    `  | {kind: 'alert'; text: string}\n` +
    `  | {kind: 'locked'; text: string; sub: string}\n` +
    `  | {kind: 'sum'; text: string}\n` +
    `  | {kind: 'cracked'; text: string};\n\n` +
    `export type Shot = {\n  from: number;\n  durationInFrames: number;\n` +
    `  still: number | null;\n  gap: number | null;\n  card: any | null;\n` +
    `  move: Move;\n  cold: boolean;\n` +
    `  figureY: number;\n  cap: string | null;\n  num: Num | null;\n};\n\n` +
    `export const SHOTS: Shot[] = ${JSON.stringify(shots, null, 2)};\n`
);

// ── subtitles ────────────────────────────────────────────────────────────────
// The spoken words, not the burn-in captions. Captions are compressed to fit a
// 1080px column; the subtitle track has to be what the narrator actually says,
// because that is what it is for — accessibility, and the text YouTube indexes.
const lines = readFileSync(path.resolve('../klarna-scene-pack.txt'), 'utf8')
  .split('\n')
  .slice(82, 141)
  .filter((l) => l.trim())
  .map((l) => l.replace(/\[[a-z]+\]\s*/g, '').trim());
const align = JSON.parse(readFileSync(path.resolve('scripts/klarna-align.json'), 'utf8'));

const ts = (s) => {
  const ms = Math.round(s * 1000);
  const p = (n, w = 2) => String(n).padStart(w, '0');
  return `${p(Math.floor(ms / 3600000))}:${p(Math.floor(ms / 60000) % 60)}:${p(
    Math.floor(ms / 1000) % 60
  )},${p(ms % 1000, 3)}`;
};
writeFileSync(
  path.resolve('../media/klarna.srt'),
  align
    .map((a, i) => `${i + 1}\n${ts(a.start)} --> ${ts(a.end)}\n${lines[a.i] ?? a.text}\n`)
    .join('\n')
);

console.log(`stills     → public/broll/klarna/ (16)`);
console.log(`voiceover  → ../media/klarna-vo.m4a (whole, ${TOTAL}s)`);
console.log(`timing     → src/klarna/timing.ts (${shots.length} shots, ${totalFrames} frames)`);
console.log(`captions   → ../media/klarna.srt (${align.length} cues)`);
console.log(
  `gap frames → ${gapsFound}/31 generated` +
    (gapsFound < 31 ? ` — the rest still fall back to a blurred reuse` : ` — all wired`)
);
