// Finds the hard cuts that are already in the Inflation footage.
//
// The footage is AI-generated (Dreamina) as a run of 3-5s scenes butt-joined
// together, so the cuts are real discontinuities, not dissolves. Every graphic
// beat and caption change in the composition is keyed to one of these frames,
// which is what stops the overlay from fighting the picture.
//
// Why not ffmpeg's scene detector: Remotion's bundled ffmpeg is built with
// --disable-filters and a whitelist that does not include `select` or
// `showinfo`, so `select='gt(scene,N)'` is not available. Neither is the
// `rawvideo` muxer. Instead the video is decoded once to a tiny greyscale
// stream through image2pipe and the frame-to-frame delta is computed here.
// That is more transparent anyway — the whole difference curve is visible,
// and the threshold is ours to set.
//
// Usage: node scripts/detect-cuts.mjs [--threshold 0.14] [--write]
//   without --write it only prints, so you can sanity-check the list first.

import {spawnSync} from 'child_process';
import {writeFileSync} from 'fs';

const FFMPEG = 'node_modules/@remotion/compositor-linux-x64-gnu/ffmpeg';
const SRC = 'public/inflation.mp4';
const OUT = 'src/inflation/cuts.ts';
const FPS = 24;

// Downscale for the delta pass. 64x114 keeps the source's 0.558 aspect and is
// coarse enough that codec noise and small motion vanish, while a whole-frame
// image change still lands hard.
const CW = 64;
const CH = 114;

const arg = (name, fallback) => {
  const i = process.argv.indexOf(name);
  return i === -1 ? fallback : Number(process.argv[i + 1]);
};
const THRESHOLD = arg('--threshold', 0.14);
const WRITE = process.argv.includes('--write');

// A cut cannot be followed by another cut a few frames later — that is one
// transition being counted twice. The footage's own scenes are 3-5s.
const MIN_GAP = Math.round(FPS * 0.7);

const r = spawnSync(
  FFMPEG,
  [
    '-hide_banner', '-loglevel', 'error',
    '-i', SRC,
    '-an',
    '-vf', `scale=${CW}:${CH}`,
    // This build has no `rawvideo` muxer, but image2pipe with the rawvideo
    // codec writes bare frames back to back, which is the same thing.
    '-f', 'image2pipe', '-c:v', 'rawvideo', '-pix_fmt', 'gray',
    '-',
  ],
  {maxBuffer: 512 * 1024 * 1024, encoding: 'buffer'},
);
if (r.status !== 0) {
  console.error(r.stderr?.toString().slice(-2000));
  process.exit(1);
}

const buf = r.stdout;
const frameSize = CW * CH;
const frames = Math.floor(buf.length / frameSize);
if (frames < 2) {
  console.error(`decoded only ${frames} frames — check ${SRC}`);
  process.exit(1);
}

// Mean absolute luma difference per frame pair, normalised 0..1.
const delta = new Float64Array(frames);
for (let f = 1; f < frames; f++) {
  const a = f * frameSize;
  const b = a - frameSize;
  let sum = 0;
  for (let i = 0; i < frameSize; i++) sum += Math.abs(buf[a + i] - buf[b + i]);
  delta[f] = sum / frameSize / 255;
}

const cuts = [0];
for (let f = 1; f < frames; f++) {
  if (delta[f] >= THRESHOLD && f - cuts[cuts.length - 1] >= MIN_GAP) cuts.push(f);
}

// A cut landing in the last half-second is a fade-out or a stray final frame,
// not a scene. Nothing can be staged in it, so fold it into the scene before.
while (cuts.length > 1 && frames - cuts[cuts.length - 1] < MIN_GAP) cuts.pop();

const sorted = [...delta].sort((x, y) => y - x);
console.log(`frames=${frames}  threshold=${THRESHOLD}`);
console.log(`top deltas: ${sorted.slice(0, 30).map((d) => d.toFixed(3)).join(' ')}`);
console.log(`\n${cuts.length} scenes:`);
cuts.forEach((f, i) => {
  const end = i + 1 < cuts.length ? cuts[i + 1] : frames;
  console.log(
    `  ${String(i).padStart(2)}  frame ${String(f).padStart(4)}  ` +
      `${(f / FPS).toFixed(2)}s  len ${((end - f) / FPS).toFixed(2)}s  ` +
      `delta ${delta[f].toFixed(3)}`,
  );
});

if (!WRITE) {
  console.log('\n(dry run — pass --write to emit src/inflation/cuts.ts)');
  process.exit(0);
}

const body = `// GENERATED by scripts/detect-cuts.mjs — do not edit by hand.
//
// Frame index of every hard cut already present in public/inflation.mp4,
// at ${FPS}fps. CUTS[0] is 0 (the first scene starts at the top of the film).
// Graphic beats and caption changes are snapped to these so the overlay lands
// with the picture instead of across it.
//
// Detected with a mean-absolute-luma delta at ${CW}x${CH}, threshold ${THRESHOLD},
// minimum ${MIN_GAP} frames between cuts.

export const SOURCE_FPS = ${FPS};
export const SOURCE_FRAMES = ${frames};

export const CUTS = [
${cuts.map((f) => `  ${f}, // ${(f / FPS).toFixed(2)}s`).join('\n')}
];

/** Length of scene i, in frames. */
export const sceneLength = (i: number) =>
  (i + 1 < CUTS.length ? CUTS[i + 1] : SOURCE_FRAMES) - CUTS[i];

/** Index of the scene that contains \`frame\`. */
export const sceneAt = (frame: number) => {
  let i = 0;
  while (i + 1 < CUTS.length && CUTS[i + 1] <= frame) i++;
  return i;
};

/** Nearest cut to \`frame\`, but only if it is within \`window\` frames. */
export const snapToCut = (frame: number, window = 8) => {
  let best = frame;
  let bestD = Infinity;
  for (const c of CUTS) {
    const d = Math.abs(c - frame);
    if (d < bestD) {
      bestD = d;
      best = c;
    }
  }
  return bestD <= window ? best : frame;
};
`;
writeFileSync(OUT, body);
console.log(`\nwrote ${OUT}`);
