"""Exports exact advance widths for the caption face.

Caption size is chosen by simulating how a phrase wraps. Doing that from an
assumed average character width is what broke the first pass: wrapping is
word-based, so "you would never buy" fell to four lines where an even
character split predicted two, and the block overran its band by 200px.
These are the real advances, read from the font that actually renders.
"""
import json
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

SRC = Path('public/fonts/inter-var.woff2')
OUT = Path('src/pension/metrics.ts')
WEIGHT = 900  # captions are set in the heaviest weight

font = TTFont(SRC)
if 'fvar' in font:
    font = instantiateVariableFont(font, {'wght': WEIGHT}, updateFontNames=False)

upem = font['head'].unitsPerEm
cmap = font.getBestCmap()
hmtx = font['hmtx']

# Chromium's line box uses the font's own ascent/descent. With line-height
# below that, ink overflows the box — which is why phrases measured ~20px
# taller than their computed block. Exported so the sizer can budget for it.
hhea = font['hhea']
content_em = round((hhea.ascent - hhea.descent) / upem, 5)

# Captions are rendered with text-transform: lowercase, so only the lowercase
# forms and the punctuation the pack actually uses can appear.
chars = set("abcdefghijklmnopqrstuvwxyz0123456789 .,!?'\"()·%-—’“”$&/:;+")
widths = {}
for ch in sorted(chars):
    gname = cmap.get(ord(ch))
    if gname is None:
        continue
    widths[ch] = round(hmtx[gname][0] / upem, 5)

OUT.write_text(
    '// GENERATED by scripts/font-metrics.py — do not edit by hand.\n'
    f'// Advance widths in em for Inter at wght {WEIGHT}, the caption weight.\n'
    f'// Ink extent of one line, in em: Chromium sizes the line box from the\n'
    f'// font ascent+descent, so a tighter line-height lets ink spill past it.\n'
    f'export const CONTENT_EM = {content_em};\n\n'
    'export const ADVANCE: Record<string, number> = '
    + json.dumps(widths, indent=1)
    + ';\n'
)
print(f'{len(widths)} advances written to {OUT}')
print(f'content em {content_em}')
print('space', widths.get(' '), '| a', widths.get('a'), '| m', widths.get('m'), '| i', widths.get('i'))
avg = sum(widths[c] for c in 'abcdefghijklmnopqrstuvwxyz') / 26
print(f'mean lowercase advance {avg:.4f} em (the old guess was 0.58)')
