// Caption cues for the Inflation short.
//
// GENERATED by scripts/make-inflation-srt.mjs from ../inflation-script.md.
// Run `npm run captions:inflation` after writing the voiceover text; do not
// hand-edit the CUES array below, it will be overwritten.
//
// It is empty because the recording's script has not been supplied yet. The
// pipeline around it is built and tested end to end — put the voiceover prose
// in ../inflation-script.md, run the command, and the cues land here and in
// ../media/inflation.srt.
//
// How the timings are arrived at, and what that means for trusting them:
// no ASR model host is reachable from this build environment, so the words are
// not recognised — they are *placed*. ffmpeg's silencedetect measures where
// speech actually starts and stops in the recording, the script's words are
// laid across those speech runs in proportion to their length, and every cue
// boundary is then snapped to the nearest real pause and, where one is close,
// to a cut in the footage. So cue boundaries are honest; word positions inside
// a cue are interpolated. That is exactly why the captions show a whole cue at
// a time and accent one keyword, rather than sweeping a karaoke playhead across
// words it cannot actually locate.

export type Cue = {
  /** Inclusive start frame, at the composition's 24fps. */
  from: number;
  /** Exclusive end frame. */
  to: number;
  /** Cue text. Kept to two lines; `\n` is an explicit break. */
  text: string;
  /**
   * A word or phrase inside `text` to set in gold. One per cue at most — the
   * accent stops meaning anything if half the line is wearing it.
   */
  keyword?: string;
};

export const CUES: Cue[] = [];
