// Caption cues for the Inflation short.
//
// GENERATED by scripts/make-inflation-captions.mjs from ../inflation-scene-pack.txt.
// Run `npm run captions:inflation` after editing the pack; do not hand-edit the
// CUES array below, it will be overwritten.
//
// Timing here is exact, not estimated. The scene pack writes caption text per
// scene, and the footage cuts between those same scenes, so every cue's start
// and end IS a cut frame in public/inflation.mp4. Nothing is interpolated and
// no speech recognition is involved — which is what the pack asks for: "the
// caption change and the picture cut land together."
//
// The two lines come straight from the pack's CAPTION 1 / CAPTION 2 per scene.

export type Cue = {
  /** Inclusive start frame, at the composition's 24fps. Always a cut. */
  from: number;
  /** Exclusive end frame — the next cut. */
  to: number;
  /** The pack's CAPTION 1: the line that carries the point. */
  line1: string;
  /** The pack's CAPTION 2: the quieter qualifier beneath it. */
  line2?: string;
};

export const CUES: Cue[] = [
  {from: 0, to: 115, line1: 'Someone takes money from you every day', line2: 'and you never see it'}, // pack 01 · cut 0 · 0.00s
  {from: 115, to: 179, line1: 'You never see it happen', line2: 'no alert, no warning'}, // pack 02 · cut 1 · 4.79s
  {from: 179, to: 278, line1: 'No receipt. No alert. Nothing.', line2: 'it leaves no trace'}, // pack 03 · cut 2 · 7.46s
  {from: 278, to: 340, line1: 'And it\'s completely legal', line2: 'that\'s the part nobody explains'}, // pack 04 · cut 3 · 11.58s
  {from: 340, to: 453, line1: 'It\'s called inflation', line2: 'and almost everyone explains it wrong'}, // pack 05 · cut 4 · 14.17s
  {from: 453, to: 489, line1: 'You got a raise this year', line2: 'on paper, you earn more'}, // pack 06 · cut 5 · 18.88s
  {from: 489, to: 542, line1: 'You\'re still short at month end', line2: 'every single month'}, // pack 07 · cut 6 · 20.38s
  {from: 542, to: 607, line1: 'That\'s not bad budgeting', line2: 'it\'s arithmetic'}, // pack 08 · cut 7 · 22.58s
  {from: 607, to: 665, line1: 'Ten years ago this filled a cart', line2: 'same note, same value printed'}, // pack 09 · cut 8 · 25.29s
  {from: 665, to: 721, line1: 'Today it fills half a bag', line2: 'identical note, half the goods'}, // pack 10 · cut 9 · 27.71s
  {from: 721, to: 778, line1: 'The note didn\'t change', line2: 'it\'s the same paper'}, // pack 11 · cut 10 · 30.04s
  {from: 778, to: 850, line1: 'How MANY of them exist did', line2: 'that\'s the whole trick'}, // pack 12 · cut 11 · 32.42s
  {from: 850, to: 950, line1: 'Money isn\'t printed', line2: 'it\'s LENT into existence'}, // pack 13 · cut 12 · 35.42s
  {from: 950, to: 992, line1: 'A bank approves a loan', line2: 'one signature'}, // pack 14 · cut 13 · 39.58s
  {from: 992, to: 1043, line1: 'and the money appears', line2: 'out of nothing'}, // pack 15 · cut 14 · 41.33s
  {from: 1043, to: 1084, line1: 'It didn\'t come from a vault', line2: 'there was nothing in there'}, // pack 16 · cut 15 · 43.46s
  {from: 1084, to: 1139, line1: 'It was typed into a screen', line2: 'that\'s the entire act'}, // pack 17 · cut 16 · 45.17s
  {from: 1139, to: 1206, line1: 'Every loan creates new money', line2: 'multiplied across millions'}, // pack 18 · cut 17 · 47.46s
  {from: 1206, to: 1278, line1: 'But the world\'s bread didn\'t multiply', line2: 'the goods stayed the same'}, // pack 19 · cut 18 · 50.25s
  {from: 1278, to: 1334, line1: 'More money. Same bread.', line2: 'that\'s all inflation is'}, // pack 20 · cut 19 · 53.25s
  {from: 1334, to: 1386, line1: 'So bread costs more', line2: 'and your wage doesn\'t move'}, // pack 21 · cut 20 · 55.58s
  {from: 1386, to: 1425, line1: 'Nobody voted for this', line2: 'no ballot, no debate'}, // pack 22 · cut 21 · 57.75s
  {from: 1425, to: 1475, line1: 'Nobody sent you a bill', line2: 'it doesn\'t arrive by post'}, // pack 23 · cut 22 · 59.38s
  {from: 1475, to: 1511, line1: 'But you paid it', line2: 'every day, without noticing'}, // pack 24 · cut 23 · 61.46s
  {from: 1511, to: 1583, line1: 'This is the tax nobody voted for', line2: 'and it never stops'}, // pack 25 · cut 24 · 62.96s
  {from: 1583, to: 1655, line1: 'The engine behind it is interest', line2: 'riba'}, // pack 26 · cut 25 · 65.96s
  {from: 1655, to: 1767, line1: 'Debt creates money', line2: 'money loses value'}, // pack 27 · cut 26 · 68.96s
  {from: 1767, to: 1851, line1: 'Value the saver never agreed to lose', line2: 'no consent was ever asked'}, // pack 28 · cut 27 · 73.63s
  {from: 1851, to: 1923, line1: 'Which is why sound money mattered', line2: 'gold and silver'}, // pack 29 · cut 28 · 77.13s
  {from: 1923, to: 1990, line1: 'You cannot type gold into existence', line2: 'no screen can create it'}, // pack 30 · cut 29 · 80.13s
  {from: 1990, to: 2062, line1: 'It has to be dug, weighed, earned', line2: 'real work, real cost'}, // pack 31 · cut 30 · 82.92s
  {from: 2062, to: 2134, line1: 'Hold what cannot be diluted', line2: 'things with real weight'}, // pack 32 · cut 31 · 85.92s
  {from: 2134, to: 2199, line1: 'Real assets. Real ownership.', line2: 'things you actually hold'}, // pack 33 · cut 32 · 88.92s
  {from: 2199, to: 2276, line1: 'Not promises that quietly shrink', line2: 'not paper claims'}, // pack 34 · cut 33 · 91.63s
  {from: 2276, to: 2348, line1: 'Your money should hold its weight', line2: 'literally'}, // pack 35 · cut 34 · 94.83s
  {from: 2348, to: 2400, line1: 'Part two: the fix', line2: 'follow so you don\'t miss it'}, // pack 37 · cut 35 · 97.83s
];
