// GENERATED by scripts/detect-cuts.mjs — do not edit by hand.
//
// Frame index of every hard cut already present in public/inflation.mp4,
// at 24fps. CUTS[0] is 0 (the first scene starts at the top of the film).
// Graphic beats and caption changes are snapped to these so the overlay lands
// with the picture instead of across it.
//
// Detected with a mean-absolute-luma delta at 64x114, threshold 0.14,
// minimum 17 frames between cuts.

export const SOURCE_FPS = 24;
export const SOURCE_FRAMES = 2400;

export const CUTS = [
  0, // 0.00s
  115, // 4.79s
  179, // 7.46s
  278, // 11.58s
  340, // 14.17s
  453, // 18.88s
  489, // 20.38s
  542, // 22.58s
  607, // 25.29s
  665, // 27.71s
  721, // 30.04s
  778, // 32.42s
  850, // 35.42s
  950, // 39.58s
  992, // 41.33s
  1043, // 43.46s
  1084, // 45.17s
  1139, // 47.46s
  1206, // 50.25s
  1278, // 53.25s
  1334, // 55.58s
  1386, // 57.75s
  1425, // 59.38s
  1475, // 61.46s
  1511, // 62.96s
  1583, // 65.96s
  1655, // 68.96s
  1767, // 73.63s
  1851, // 77.13s
  1923, // 80.13s
  1990, // 82.92s
  2062, // 85.92s
  2134, // 88.92s
  2199, // 91.63s
  2276, // 94.83s
  2348, // 97.83s
];

/** Length of scene i, in frames. */
export const sceneLength = (i: number) =>
  (i + 1 < CUTS.length ? CUTS[i + 1] : SOURCE_FRAMES) - CUTS[i];

/** Index of the scene that contains `frame`. */
export const sceneAt = (frame: number) => {
  let i = 0;
  while (i + 1 < CUTS.length && CUTS[i + 1] <= frame) i++;
  return i;
};

/** Nearest cut to `frame`, but only if it is within `window` frames. */
export const snapToCut = (frame: number, window = 8) => {
  let best = frame;
  let bestD = Infinity;
  for (const c of CUTS) {
    const d = Math.abs(c - frame);
    if (d < bestD) {
      bestD = d;
      best = c;
    }
  }
  return bestD <= window ? best : frame;
};
