/**
 * GENERATED by scripts/make-vo.mjs — do not edit by hand.
 *
 * Measured from the audio in public/.
 * full: 64.31s / 1929 frames — master (full.mp3)
 * short: 46.68s / 1400 frames — Kokoro am_michael @ 1x
 *
 * Re-run `npm run vo` after any change to scripts/vo-cuts.mjs.
 */
export const VO = {
  full: {
    /** master (full.mp3) */
    audio: 'vo-source/full.mp3',
    totalFrames: 1929,
    /** How many rows of the lending chain this read actually narrates. */
    chainRows: 5,
    beats: {
      balance: { from: 0, durationInFrames: 296 },
      vault: { from: 296, durationInFrames: 179 },
      cascade: { from: 475, durationInFrames: 288 },
      owners: { from: 763, durationInFrames: 265 },
      run: { from: 1028, durationInFrames: 253 },
      assets: { from: 1281, durationInFrames: 335 },
      kicker: { from: 1616, durationInFrames: 313 },
    },
    cues: {
      /** frames into the balance beat where line 2 starts */
      rollStart: 174,
      /** frames into the run beat where the shutter lands */
      slam: 239,
    },
    lines: [
      { n: 1, beat: 'balance' },
      { n: 2, beat: 'balance' },
      { n: 3, beat: 'vault' },
      { n: 4, beat: 'cascade' },
      { n: 5, beat: 'owners' },
      { n: 6, beat: 'run' },
      { n: 7, beat: 'assets' },
      { n: 8, beat: 'kicker' },
    ],
  },
  short: {
    /** Kokoro am_michael @ 1x */
    audio: 'vo-short.mp3',
    totalFrames: 1400,
    /** How many rows of the lending chain this read actually narrates. */
    chainRows: 2,
    beats: {
      balance: { from: 5, durationInFrames: 281 },
      vault: { from: 286, durationInFrames: 95 },
      cascade: { from: 381, durationInFrames: 187 },
      owners: { from: 568, durationInFrames: 190 },
      run: { from: 757, durationInFrames: 166 },
      assets: { from: 923, durationInFrames: 209 },
      kicker: { from: 1132, durationInFrames: 267 },
    },
    cues: {
      /** frames into the balance beat where line 2 starts */
      rollStart: 155,
      /** frames into the run beat where the shutter lands */
      slam: 153,
    },
    lines: [
      { n: 1, beat: 'balance' },
      { n: 2, beat: 'balance' },
      { n: 3, beat: 'vault' },
      { n: 4, beat: 'cascade' },
      { n: 5, beat: 'owners' },
      { n: 6, beat: 'run' },
      { n: 7, beat: 'assets' },
      { n: 8, beat: 'kicker' },
    ],
  },
} as const;

export type Cut = keyof typeof VO;
