/**
 * GENERATED by scripts/make-vo.mjs — do not edit by hand.
 *
 * Measured from public/vo.mp3 (Kokoro am_michael @ 0.96x).
 * Total 64.25s / 1927 frames at 30fps.
 *
 * Re-run `npm run vo` after any change to a line, a pause, or the voice.
 */
export const VO = {
  totalFrames: 1927,
  beats: {
    balance: { from: 6, durationInFrames: 301 },
    vault: { from: 307, durationInFrames: 176 },
    cascade: { from: 483, durationInFrames: 287 },
    owners: { from: 769, durationInFrames: 267 },
    run: { from: 1037, durationInFrames: 251 },
    assets: { from: 1288, durationInFrames: 335 },
    kicker: { from: 1623, durationInFrames: 304 },
  },
  cues: {
    /** frames into the balance beat where line 2 starts */
    rollStart: 165,
    /** frames into the run beat where the shutter lands */
    slam: 232,
  },
  lines: [
    { n: 1, beat: 'balance', spoken: 4.949, pad: 0.55 },
    { n: 2, beat: 'balance', spoken: 3.733, pad: 0.8 },
    { n: 3, beat: 'vault', spoken: 5.355, pad: 0.5 },
    { n: 4, beat: 'cascade', spoken: 9.109, pad: 0.45 },
    { n: 5, beat: 'owners', spoken: 8.256, pad: 0.65 },
    { n: 6, beat: 'run', spoken: 7.872, pad: 0.5 },
    { n: 7, beat: 'assets', spoken: 10.667, pad: 0.5 },
    { n: 8, beat: 'kicker', spoken: 9.003, pad: 1.1 },
  ],
} as const;
