/**
 * GENERATED by scripts/make-vo.mjs — do not edit by hand.
 *
 * Measured from the audio in public/ (Kokoro am_michael).
 * full: 64.25s / 1927 frames @ 0.96x
 * short: 46.68s / 1400 frames @ 1x
 *
 * Re-run `npm run vo` after any change to scripts/vo-cuts.mjs.
 */
export const VO = {
  full: {
    audio: 'vo-full.mp3',
    totalFrames: 1927,
    /** How many rows of the lending chain this read actually narrates. */
    chainRows: 5,
    beats: {
      balance: { from: 6, durationInFrames: 301 },
      vault: { from: 307, durationInFrames: 176 },
      cascade: { from: 483, durationInFrames: 287 },
      owners: { from: 769, durationInFrames: 267 },
      run: { from: 1037, durationInFrames: 251 },
      assets: { from: 1288, durationInFrames: 335 },
      kicker: { from: 1623, durationInFrames: 304 },
    },
    cues: {
      /** frames into the balance beat where line 2 starts */
      rollStart: 165,
      /** frames into the run beat where the shutter lands */
      slam: 232,
    },
    lines: [
      { n: 1, beat: 'balance', spoken: 4.949, pad: 0.55 },
      { n: 2, beat: 'balance', spoken: 3.733, pad: 0.8 },
      { n: 3, beat: 'vault', spoken: 5.355, pad: 0.5 },
      { n: 4, beat: 'cascade', spoken: 9.109, pad: 0.45 },
      { n: 5, beat: 'owners', spoken: 8.256, pad: 0.65 },
      { n: 6, beat: 'run', spoken: 7.872, pad: 0.5 },
      { n: 7, beat: 'assets', spoken: 10.667, pad: 0.5 },
      { n: 8, beat: 'kicker', spoken: 9.003, pad: 1.1 },
    ],
  },
  short: {
    audio: 'vo-short.mp3',
    totalFrames: 1400,
    /** How many rows of the lending chain this read actually narrates. */
    chainRows: 2,
    beats: {
      balance: { from: 5, durationInFrames: 281 },
      vault: { from: 286, durationInFrames: 95 },
      cascade: { from: 381, durationInFrames: 187 },
      owners: { from: 568, durationInFrames: 190 },
      run: { from: 757, durationInFrames: 166 },
      assets: { from: 923, durationInFrames: 209 },
      kicker: { from: 1132, durationInFrames: 267 },
    },
    cues: {
      /** frames into the balance beat where line 2 starts */
      rollStart: 155,
      /** frames into the run beat where the shutter lands */
      slam: 153,
    },
    lines: [
      { n: 1, beat: 'balance', spoken: 4.779, pad: 0.4 },
      { n: 2, beat: 'balance', spoken: 3.605, pad: 0.6 },
      { n: 3, beat: 'vault', spoken: 2.816, pad: 0.35 },
      { n: 4, beat: 'cascade', spoken: 5.931, pad: 0.3 },
      { n: 5, beat: 'owners', spoken: 5.867, pad: 0.45 },
      { n: 6, beat: 'run', spoken: 5.227, pad: 0.3 },
      { n: 7, beat: 'assets', spoken: 6.613, pad: 0.35 },
      { n: 8, beat: 'kicker', spoken: 7.979, pad: 0.9 },
    ],
  },
} as const;

export type Cut = keyof typeof VO;
